### ISSUE TITLE
运行vis4val.py时出错 Key Error 求解~

### ISSUE THREAD

**Issue by lizxko2009** [taohan10200/IIM#16]
(IIM) E:\IIM-main\IIM>python vis4val.py
3110
Traceback (most recent call last):
  File "vis4val.py", line 101, in <module>
    main()
  File "vis4val.py", line 34, in main
    if gt_data[i_sample]['num'] ==0 and pred_data[i_sample]['num'] !=0:
KeyError: 3110

**Comment by taohan10200** [comment]
请确认val_gt_loc.txt和生成的预测文件的格式，如下:
pred.txt
3110+人数 + 预测的人头坐标(x, y)
3111 .......
...............
val_gt_loc.txt
3110 + 人数 +人头的位置和size信息(x, y, sigma_s, sigma_l, level)
3111 ......
.................
其中，3110,3111对应着NWPU数据集里图片的ID
